### ISSUE TITLE
完成对象后多边形的编号改变

### ISSUE THREAD

**Issue by geoyee** [PaddleCV-SIG/EISeg#11]
问题大概出在app.py978行。这个问题将导致保留最大联通区和重加载多边形后修改产生多边形标签改变或越界问题。

**Comment by linhandev** [comment]
问题描述：保存标签，重新加载，切换图片 -> 标签id变化

**Comment by linhandev** [comment]
我觉得这个问题可能等我今天做完cooc格式保存之后看一下怎么解决，保存那个自己的json用户用起来很不方便。存完了看看怎么恢复会比较好，肯定是要对用户有一些要求，比如还加载之前的标签文件之类的

**Comment by linhandev** [comment]
coco save加了，可以看一下还有没有这问题

**Comment by geoyee** [comment]
> coco save加了，可以看一下还有没有这问题

这个没问题了
