### ISSUE TITLE
快捷键编辑窗口弹出位置问题

### ISSUE THREAD

**Issue by linhandev** [PaddleCV-SIG/EISeg#15]
按下e之后弹出来的这个窗口一直不在屏幕中间，能不能研究一下让他居中

**Comment by geoyee** [comment]
> 按下e之后弹出来的这个窗口一直不在屏幕中间，能不能研究一下让他居中

了解

**Comment by geoyee** [comment]
看看现在居中了吗，平板上感觉不是很清楚

**Comment by linhandev** [comment]
差不多，比之前好多了，晚上让莹姐看一眼
