### ISSUE TITLE
标签覆盖问题

### ISSUE THREAD

**Issue by linhandev** [PaddleCV-SIG/EISeg#16]
目前实现是按照标注顺序，后面的盖前面的，考虑要不要实现按照标签序号顺序，大号的盖小号，或者反过来

**Comment by geoyee** [comment]
要不给label的tabellist加一个拖动，可以拖动每个类别在list中的顺序，这样就可以按照这个tabellist的顺序来覆盖了

**Comment by geoyee** [comment]
> 目前实现是按照标注顺序，后面的盖前面的，考虑要不要实现按照标签序号顺序，大号的盖小号，或者反过来

韩兄现在拖动name那一列是可以交换两行的标签的位置。但是现在只有在没有完成的情况下图层的顺序会随着标签栏顺序改变而改变。现在想的在完成了全部对象后，拖动改变标签栏的顺序应该要可以实时改变多边形的叠加顺序。这里我还没看到在哪儿，韩兄有空可以搞一下看看这样的覆盖如何（大约在app.py 873行）

**Comment by geoyee** [comment]
ok可以试试了，拖动tableitem（按住name那一格），最后从上往下覆盖
