### ISSUE TITLE
多个孔洞的图片会保存失败

### ISSUE THREAD

**Issue by haoyuying** [PaddleCV-SIG/EISeg#17]
![image](https://user-images.githubusercontent.com/35907364/127298702-9ac81e02-97eb-4620-bb94-d92c1096233e.png)

![image](https://user-images.githubusercontent.com/35907364/127299544-58eae355-22e1-4c7c-a982-da7383410359.png)

这张图b标红色的车厢把车窗抠出来的时候。

**Comment by geoyee** [comment]
> ![image](https://user-images.githubusercontent.com/35907364/127298702-9ac81e02-97eb-4620-bb94-d92c1096233e.png)
> 
> ![image](https://user-images.githubusercontent.com/35907364/127299544-58eae355-22e1-4c7c-a982-da7383410359.png)
> 
> 这张图b标红色的车厢把车窗抠出来的时候。

是的目前内部孔洞大于1个的时候这样连接会出现问题

**Comment by geoyee** [comment]
现在应该是不会报错了，虽然那个线看起来不太美观
![B2UWGZWRI@YQ96FD5TP$MEU](https://user-images.githubusercontent.com/71769312/127609933-4e16fa16-4936-4ea5-8759-68ba7080f73d.png)

**Comment by geoyee** [comment]
考虑中间的线不连接

**Comment by linhandev** [comment]
working on this
