### ISSUE TITLE
undo/redo 图标

### ISSUE THREAD

**Issue by linhandev** [PaddleCV-SIG/EISeg#19]
感觉undo/redo图标如果换成那种word里常见的，一个曲线，一个箭头，可能更直观一些

比如这种
![image](https://user-images.githubusercontent.com/29757093/127664067-d54d0cd2-0c76-4dee-8db2-e32c1a6bbfeb.png)

**Comment by geoyee** [comment]
> 感觉undo/redo图标如果换成那种word里常见的，一个曲线，一个箭头，可能更直观一些
> 
> 比如这种
> ![image](https://user-images.githubusercontent.com/29757093/127664067-d54d0cd2-0c76-4dee-8db2-e32c1a6bbfeb.png)

ok了
