### ISSUE TITLE
使用过程中，GPU显存占用会越来越大。

### ISSUE THREAD

**Issue by CN-Anan** [PaddleCV-SIG/EISeg#22]
使用过程中，GPU显存占用会越来越大。

**Comment by geoyee** [comment]
了解，针对这个问题将进行检查和优化

**Comment by geoyee** [comment]
> 使用过程中，GPU显存占用会越来越大。

了解，针对这个问题将进行检查和优化

**Comment by geoyee** [comment]
> 使用过程中，GPU显存占用会越来越大。

这个目前应该就是这样了。他只有在关闭后才会释放。我试了试应该影响不大，后面再看看有没有更好的解决办法。
