### ISSUE TITLE
EISEG的菜单栏功能

### ISSUE THREAD

**Issue by ZHANGZHANG407** [PaddleCV-SIG/EISeg#25]
![图片](https://user-images.githubusercontent.com/88808381/129122301-9ee155eb-e0a7-4d51-91bc-af09e78aa49c.png)
之前通过pycharm运行eiseg时菜单栏有许多功能，比如选择是否适用于遥感图像，但是现在打开eiseg时菜单栏只剩下文件和标注这两个功能，请问如何运行回到原来的状态？

**Comment by geoyee** [comment]
试试重新clone看看，看这个界面应该是paddleseg下的EISeg

**Comment by geoyee** [comment]
> ![图片](https://user-images.githubusercontent.com/88808381/129122301-9ee155eb-e0a7-4d51-91bc-af09e78aa49c.png)
> 之前通过pycharm运行eiseg时菜单栏有许多功能，比如选择是否适用于遥感图像，但是现在打开eiseg时菜单栏只剩下文件和标注这两个功能，请问如何运行回到原来的状态？

试试重新clone看看，看这个界面应该是paddleseg下的EISeg

**Comment by linhandev** [comment]
paddleseg下面的eiseg是一个稳定的旧版本，这个repo是最新的开发版，功能会有一些差异
