### ISSUE TITLE
修改了多边形点位置，切换下一张图自动保存无效

### ISSUE THREAD

**Issue by geoyee** [PaddleCV-SIG/EISeg#31]
如题，只修改点的位置，切换下一张图再切换回来点还原，没有保存（开启自动保存不识别点移动）

**Comment by linhandev** [comment]
是有这个问题，动了点之后没有设dirty，正在解决

**Comment by linhandev** [comment]
唉，这个问题还有吗，我记得应该fix过🤔

**Comment by yharby** [comment]
@linhandev yes, I think we can label it as solved.

**Comment by linhandev** [comment]
@Youssef-Harby maybe can try it out, if it is solved just close this.
Many thanks
