### ISSUE TITLE
Could give *.ui file to update GUI?

### ISSUE THREAD

**Issue by bio-punk** [PaddleCV-SIG/EISeg#48]
For example, There is no *.ui file to update GUI design in "/contrib/EIseg/*", So I cannot add a button in this program.Thank you very much!

各位大牛们，能不能提供一下EIseg的UI文件啊，想往上加个按钮，求求了，谢谢大家！

**Comment by geoyee** [comment]
都在里面，有个ui.py，里面是基本的界面，然后工具栏菜单栏等等的在app.py动态添加的。相关的创建方法可以通过搜索找到。
