### ISSUE TITLE
如何标注相邻的两个物体

### ISSUE THREAD

**Issue by GY0913** [PaddleCV-SIG/EISeg#51]
比如上衣和裤子，标注出上衣后标裤子的时候上衣区域不能再标为负样本点，裤子的整体轮廓会包含上衣点集

**Comment by geoyee** [comment]
> 比如上衣和裤子，标注出上衣后标裤子的时候上衣区域不能再标为负样本点，裤子的整体轮廓会包含上衣点集

空格可以改变标注状态，当标注完上衣后空格生成多边形，此时内部是有颜色的，再次使用空格内部就会变成透明的，此时标注裤子时就可以在上衣的区域添加负点了
