### ISSUE TITLE
json

### ISSUE THREAD

**Issue by Ab-123** [PaddleCV-SIG/EISeg#6]
标注保存的json文件和coco数据集json文件格式有什么区别，

**Comment by Ab-123** [comment]
怎么将保存的json文件转化为coco格式

**Comment by linhandev** [comment]
目前的json和coco没有关系，这个json就是最简单的保存了目标的位置，id和颜色，目的让软件在翻过一张图片之后再翻回来可以重新展示之前的多边形。目前还有不少其他的地方需要修改所以这块先实现了一个简单的版本，coco和voc预计这周会研究至少上一个。

**Comment by fyj1** [comment]
这个json可以转成yolo吗，他和readme保存的json有区别吗

**Comment by fyj1** [comment]
这个json可以转成yolo吗，他和labelme保存的json有区别吗
