### ISSUE TITLE
重新打开软件后再加载之前的图片，以前的标注信息没有了

### ISSUE THREAD

**Issue by ly0303521** [PaddleCV-SIG/EISeg#7]
你好，工具很好用，但是每次关闭软件之后再加载以前的数据，以前的标注信息不能自动识别并显示出来，请问是我哪里没设置好，还是暂时没有实现这个功能

**Comment by geoyee** [comment]
> 你好，工具很好用，但是每次关闭软件之后再加载以前的数据，以前的标注信息不能自动识别并显示出来，请问是我哪里没设置好，还是暂时没有实现这个功能

你好，目前这个功能还没有做，近期将会进行完善。

**Comment by ly0303521** [comment]
刚刚测试了，需要重启的时候选择 “改变标签保存路径”， 就可以加载以前的标签数据了

**Comment by geoyee** [comment]
> 刚刚测试了，需要重启的时候选择 “改变标签保存路径”， 就可以加载以前的标签数据了

确实哈，我还以为没有准备加上，看来大佬已经加了，不好意思了

**Comment by linhandev** [comment]
在运行过程中进行标签列表的保存或从文件加载都会把标签文件的路径存到软件配置里，下次启动自动加载回来
