### ISSUE TITLE
对以前标注好的图片再进行保存操作，会直接报错闪退

### ISSUE THREAD

**Issue by ly0303521** [PaddleCV-SIG/EISeg#8]
如题，闪退的原因应该是保存时，标签列表越界了

**Comment by ly0303521** [comment]
找到原因了，在保存的时候有些 labelIdx 值不对， 但为什么 labelIdx 会写错，目前还不清楚

**Comment by geoyee** [comment]
> 找到原因了，在保存的时候有些 labelIdx 值不对， 但为什么 labelIdx 会写错，目前还不清楚

收到问题了，试了一下确实，感谢，将尽快解决

**Comment by ly0303521** [comment]
@geoyee 根本原因找到了，原因是 ui.py  Class PolygonAnnotation 里面， self.labelIndex = index导致，因为label需要是从1开始，但是self.labelIndex是从0开始，每次重启之后会加载这个类，导致类别索引出错，改成  self.labelIndex = index - 1， 就不会报错了
