### ISSUE TITLE
重名覆盖

### ISSUE THREAD

**Issue by linhandev** [PaddleCV-SIG/EISeg#9]
两张文件名相同，只有格式不同的图片在保存的时候标签都会存成 文件名.png，会互相覆盖

**Comment by linhandev** [comment]
注意名字中间带点的情况

**Comment by geoyee** [comment]
> 注意名字中间带点的情况

这个已经搞定了

**Comment by geoyee** [comment]
> 两张文件名相同，只有格式不同的图片在保存的时候标签都会存成 文件名.png，会互相覆盖

这个感觉就自己注意不要吧。。因为加载多边形也是根据这个来的

**Comment by geoyee** [comment]
> 两张文件名相同，只有格式不同的图片在保存的时候标签都会存成 文件名.png，会互相覆盖

感觉这个只有自己注意不用重名吧。。因为加载多边形也是根据名字来的。要不加一个判断吗，有重名的就警告？

**Comment by linhandev** [comment]
设成了有重名的时候所有标签都保留文件的后缀。当时反馈这个问题的那个人是标的爬的数据，就很多这种重的。保存的细节我写了一下[在这](https://github.com/PaddleCV-SIG/EISeg/wiki/%E6%A0%87%E7%AD%BE%E4%BF%9D%E5%AD%98)
